config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :picks
  end
  root "pages#home"

  get 'pages/home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  namespace :api do
    get 'leaderboard', to: 'api#leaderboard'
    get 'events', to: 'api#events'
    get 'events/:event_id', to: 'api#event'
    get 'events/:event_id/picks', to: 'api#get_picks'
    post 'events/:event_id/picks', to: 'api#update_picks'
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :ninjas, dependent: :destroy
  has_many :picks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[ show index ]
  before_action :check_organizer, only: %i[ new edit create update destroy ]
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    ActiveRecord::Base.transaction do
      @event.save!
      update_ninjas(@event, ninja_params[:male], 'male')
      update_ninjas(@event, ninja_params[:female], 'female')
    end

    respond_to do |format|
      format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
      format.json { render :show, status: :created, location: @event }
    end

  rescue Exception => ex
    respond_to do |format|
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @event.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    ActiveRecord::Base.transaction do
      @event.update!(event_params)
      update_ninjas(@event, ninja_params[:male], 'male')
      update_ninjas(@event, ninja_params[:female], 'female')
    end

    respond_to do |format|
      format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
      format.json { render :show, status: :created, location: @event }
    end

  rescue Exception => ex
    respond_to do |format|
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @event.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def permitted_params
      params.require(:event).permit(
        :name,
        :finished,
        :ninjas_male,
        :ninjas_female
      )
    end

    # Only allow a list of trusted parameters through.
    def event_params
      {
        name: permitted_params[:name],
        finished: permitted_params[:finished],
        user: current_user
      }
    end

    def ninja_params
      {
        male: permitted_params[:ninjas_male].split("\n").reject(&:empty?),
        female: permitted_params[:ninjas_female].split("\n").reject(&:empty?),
      }
    end

    def update_ninjas(event, names, sex)
      event.ninjas.where(sex: sex).where.not(name: names).destroy_all
      (names - event.ninjas.where(sex: sex).pluck(:name)).each do |name|
        event.ninjas.create!(name: name, sex: sex)
      end

      if event.finished?
        names.each_with_index do |name, index|
          event.ninjas.find_by(sex: sex, name: name).update!(position: index)
        end
      end
    end

    def check_organizer
      if !current_user.organizer?
        redirect_to root_url, notice: 'You must have organizer permissions to view that page.'
      end
    end

    def index_params
      params.permit(:finished)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Name:</strong>
    <%= event.name %>
  </p>

  <% if event.finished? %>
    <p>Finished</p>
  <% else %>
    <p>Upcoming</p>
  <% end %>

  <p>
    <strong>Ninjas (male)</strong>
    <% if event.finished? %>
      <ol>
    <% else %>
      <ul>
    <% end %>
      <% event.ninjas.where(sex: 'male').map do |ninja| %> 
        <li>
          <%= ninja.name %>
        </li>
      <% end %>
    <% if event.finished? %>
      </ol>
    <% else %>
      </ul>
    <% end %>
  </p>

  <p>
    <strong>Ninjas (female)</strong>
    <% if event.finished? %>
      <ol>
    <% else %>
      <ul>
    <% end %>
      <% event.ninjas.where(sex: 'female').map do |ninja| %> 
        <li>
          <%= ninja.name %>
        </li>
      <% end %>
    <% if event.finished? %>
      </ol>
    <% else %>
      </ul>
    <% end %>
  </p>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <p>
    Please enter a newline-separated list of ninja names for each field.
    You should be able to copy and paste the column from a spreadsheet.
  </p>

  <div>
    <%= form.label :ninjas_male, style: "display: block" %>
    <%= form.text_area :ninjas_male, rows: 10, value: event.ninjas.where(sex: 'male').pluck(:name).join("\n") %>
  </div>

  <div>
    <%= form.label :ninjas_female, style: "display: block" %>
    <%= form.text_area :ninjas_female, rows: 10, value: event.ninjas.where(sex: 'female').pluck(:name).join("\n") %>
  </div>

  <div>
    <p>
      When this box is checked, no more picks can be cast.
      Ninjas will be ranked in the order listed above. You should copy the results from a spreadsheet like before.
      Warning: If any names are misspelled or not included, those picks will be lost.
    </p>
    <%= form.label :finished, style: "display: block" %>
    <%= form.check_box :finished %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

<br>

<%= button_to "Destroy this event", @event, method: :delete %>

app/views/events/index.html.erb
<div id='app'></div>
<%= javascript_include_tag 'events' %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<div id='app'></div>
<%= javascript_include_tag 'event' %>