config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :picks
  end
  root "pages#home"

  get 'pages/home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  namespace :api do
    get 'leaderboard', to: 'api#leaderboard'
    get 'events', to: 'api#events'
    get 'events/:event_id', to: 'api#event'
    get 'events/:event_id/picks', to: 'api#get_picks'
    post 'events/:event_id/picks', to: 'api#update_picks'
  end
end

app/models/pick.rb
class Pick < ApplicationRecord
  belongs_to :event
  belongs_to :user
  belongs_to :ninja

  validates :placement, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than: 3
  }
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event
  before_action :set_pick, only: %i[ show edit update destroy ]
  
  # I may delete this controller entirely, but this will
  # prevent most people from accessing it
  before_action :check_organizer

  # GET /picks or /picks.json
  def index
    @picks = Pick.all
  end

  # GET /picks/1 or /picks/1.json
  def show
  end

  # GET /picks/new
  def new
    @pick = Pick.new
  end

  # GET /picks/1/edit
  def edit
  end

  # POST /picks or /picks.json
  def create
    @pick = Pick.new(
      placement: pick_params['placement'],
      ninja: Ninja.find_by(pick_params['ninja']),
      user: current_user,
      event: @event
    )

    respond_to do |format|
      if @pick.save
        format.html { redirect_to event_pick_url(@event, @pick), notice: "Pick was successfully created." }
        format.json { render :show, status: :created, location: @pick }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /picks/1 or /picks/1.json
  def update
    update_pick_params = {
      placement: pick_params['placement'],
      ninja: Ninja.find_by(pick_params['ninja']),
      user: current_user,
      event: @event
    }

    respond_to do |format|
      if @pick.update(update_pick_params)
        format.html { redirect_to event_pick_url(@event, @pick), notice: "Pick was successfully updated." }
        format.json { render :show, status: :ok, location: @pick }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /picks/1 or /picks/1.json
  def destroy
    @pick.destroy

    respond_to do |format|
      format.html { redirect_to event_picks_url(@event), notice: "Pick was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pick
      @pick = Pick.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pick_params
      params.require(:pick).permit(:placement, :ninja)
    end

    def set_event
      @event = Event.find(params[:event_id])
    end

    def check_organizer
      if !current_user.organizer?
        redirect_to root_url, notice: 'You must have organizer permissions to view that page.'
      end
    end
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/picks/_form.html.erb
<%= form_with(model: [@event, pick]) do |form| %>
  <% if pick.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pick.errors.count, "error") %> prohibited this pick from being saved:</h2>

      <ul>
        <% pick.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :placement, style: "display: block" %>
    <%= form.number_field :placement %>
  </div>

  <div>
    <%= form.label :ninja, style: "display: block" %>
    <%= form.select :ninja, options: @event.ninjas.collect {|n| [ n.name, n.id ] } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/picks/_pick.html.erb
<div id="<%= dom_id pick %>">
  <p>
    <strong>User:</strong>
    <%= pick.user.name %>
  </p>  

  <p>
    <strong>Event:</strong>
    <%= pick.event.name %>
  </p>

  <p>
    <strong>Placement:</strong>
    <%= pick.placement %>
  </p>

  <p>
    <strong>Pick:</strong>
    <%= pick.ninja.name %>
  </p>
</div>

app/views/picks/edit.html.erb
<h1>Editing pick</h1>

<%= render "form", pick: @pick %>

<br>

<div>
  <%= link_to "Show this pick", event_pick_path(@event, @pick) %> |
  <%= link_to "Back to picks", event_picks_path(@event) %>
</div>

app/views/picks/index.html.erb
<div id='app'></div>
<%= javascript_include_tag 'picks' %>

app/views/picks/new.html.erb
<h1>New pick</h1>

<%= render "form", pick: @pick %>

<br>

<div>
  <%= link_to "Back to picks", event_picks_path(@event) %>
</div>

app/views/picks/show.html.erb
<%= render @pick %>

<div>
  <%= link_to "Edit this pick", edit_event_pick_path(@pick) %> |
  <%= link_to "Back to picks", event_picks_path(@event) %>

  <%= button_to "Destroy this pick", event_pick_path(@event, @pick), method: :delete %>
</div>